### ISSUE TITLE
Registering public key

### ISSUE THREAD

**Issue by etemiz** [EOSIO/eos-token-sale#10]
I paste the address EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV  and click on register. Get this

Transaction execution error.

Error: Transaction execution error.
    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7861:27885)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7862:26989
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:168:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7838:5

Metamask 3.7.8
Version 59.0.3071.86 (Developer Build) Built on Ubuntu , running on Ubuntu 14.04 (64-bit)
Get help with Chromium

**Comment by jcalfee** [comment]
I see this too.  It happens when I call `eos.sol::register(string key)` with a valid key.

**Comment by jcalfee** [comment]
fixed https://github.com/EOSIO/eos-token-sale/commit/48897386097957b1368d3106470ebc38564feaec
