### ISSUE TITLE
Update README register-your-public-key

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos-token-sale#14]
I think this is the register section I just changed in https://github.com/EOSIO/eos-token-sale/pull/13

https://github.com/EOSIO/eos-token-sale#register-your-public-key

So would need to change this as follows..

Change:
>At any time a user can map their Etheruem address to a public key in one of the following formats:
>EOS, STEEM, BTS, 

To:
> At any time a user can generate a new EOS private key and map their Etheruem address to this key.

**Comment by jcalfee** [comment]
Calling the contract directly will allow these other key types but the token sale UI only generates the EOS key type.

**Comment by ibbys** [comment]
Register key keeps looping

**Comment by Tatx13** [comment]
what do i need to do please?

**Comment by jcalfee** [comment]
This issue is really not an issue.  I was just making sure the working is correct.

Please create another ticket and provide as much information as possible..  I'll make sure the right people see it.
