### ISSUE TITLE
[Suggestion] Better compatible with non-browser environment

### ISSUE THREAD

**Issue by wujunchuan** [EOSIO/eos-token-sale#33]
In some development environment (such as WeChat applets, etc.) doesn't include the `window` object. If passed directly to determine whether there is a `crypto` or `msCrypto` object.These environments tend to report the wrong message.

Try to comment out `var crypto = window.crypto || window.msCrypto` this line,It can work fine.
I do not know why non-browser environment must call `window. Crypto` or` window. MsCrypto`
**Maybe we can remove this line to better compatible with non-browser environment.**

> update at 2018-02-25: 
WeChat applets dev tools will auto inject a `window` Object, but after compile will not include `window` Object.So caused the misunderstanding above.

![image](https://user-images.githubusercontent.com/7511631/36473856-cb1f4c4c-1730-11e8-8b3f-a1181c927dff.png)

![image](https://user-images.githubusercontent.com/7511631/36473591-e839056c-172f-11e8-9b9f-5045c13ac29a.png)

[ecc.js](https://github.com/EOSIO/eos-token-distribution/blob/master/docs/ecc.js#L14181)

**Comment by wuyahuang** [comment]
I have same error.

**Comment by wujunchuan** [comment]
have solved this problem,
just use this polyfill library: https://github.com/gaswelder/window-crypto
