### ISSUE TITLE
Who to contact for eos token distribution issue?

### ISSUE THREAD

**Issue by hhcj2016** [EOSIO/eos-token-sale#35]
Hi there, I don't know if there is any helpdesk or support stuff for eos token distribution. I have encounted issues during today's distribution, the result of eth distributed and the claimed eos number to me doesn't match. So that I'd like to see who can help me for this? Can anyone help? Many thanks in advance!

**Comment by hkshwa** [comment]
Please contact us at support@block.one for support with the distribution.

**Comment by hhcj2016** [comment]
Sorry.I made some mistake.Can anyone close this issue or delete this one?Thanks!

**Comment by hkshwa** [comment]
Issue is already closed.
