### ISSUE TITLE
Wrong Distribution Percentage on Readme

### ISSUE THREAD

**Issue by clayop** [EOSIO/eos-token-sale#4]
`700,000,000 EOS (30%) will be split evenly into 350 consecutive 23 hour windows of 2,000,000 EOS tokens each starting after the initial window.`

The percentage should be 70%

700,000,000 EOS (**70%**) will be split evenly into 350 consecutive 23 hour windows of 2,000,000 EOS tokens each starting after the initial window.

**Comment by desouzag** [comment]
I highlighted it on the slack also.
